# Example configuration file for the frameserve component
# Configuration options for each component TYPE are shown
# To use them:
#
# ``` bash
# oat frameserve TYPE SINK -c config.toml TYPE
# ```

[gige]
index = 1               # Index of camera on the bus (there can be more than one)
fps = 30.0              # Frames per second
#exposure = 0.0         # Automatically adjust shutter and gain to achieve given exposure (EV)
shutter = 3.0           # Shutter time (ms; ignored if exposure on)
gain = 10.0             # Sensor gain(dB; ignored if exposure on)
white_bal = {red = 500, blue = 800} # White balance (0-1000; if note specified, defaults to "off")
# Region of interest (pixels) 
# NOTE: I cannot find this documented anywhere, but it seems that these need to
# be even numbers!                                                                                 
roi = {x_offset = 0, y_offset = 0, width = 100, height = 100}                                  
x_bin = 2               # On-camera x-dimension pixel binning (pixels; if note specified, defaults to "off")
y_bin = 2               # On-camera y-dimension pixel binning (pixels; if note specified, defaults to "off")
trigger_on = false      # If false, free run at fps or maximum rate if that is not specified
trigger_rising = true   # Rising edge active if true. Falling edge active if false.
trigger_mode = 14       # FPGA implmented trigger mode
                        #   14 = Overlapped Exposure/Readout Mode (see Camera manual)
                        #   1  = Standard trigger
                        #   7  = Software trigger
trigger_pin = 0         # GPIO pin that trigger will be sent to
enforce_fps = false     # Ensure that frames are produced at the fps setting by retransmitting frames 
                        # if the requested period is exceeded. This is needed in the case of an external
                        # trigger because PG cameras sometimes just ignore them. I have opened a support
                        # ticket on this, but PG has no solution yet.

[file]
fps = 100.0      # Hz
roi = {x_offset = 0, y_offset = 0, width = 100, height = 100} # Region of interest (pixels)

[wcam]
index = 0               # Index of camera on the bus (there can be more than one)
roi = {x_offset = 0, y_offset = 0, width = 100, height = 100} # Region of interest (pixels)

[test]
num-samples = 1000
