language: cpp

before_script:
  - sudo apt-get update
  - sudo apt-get install libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - sudo apt-get install doxygen
  - sudo apt-get install libboost-all-dev

  # Install OpenCV 3.0
  - wget https://github.com/Itseez/opencv/archive/3.0.0.zip
  - unzip opencv-3.0.0.zip
  - cd opencv-3*
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local ..
  - make
  - sudo make install

  # RapidJSON and cpptoml
  - cd TRAVIS_BUILD_DIR
  - cd lib
  - sudo ./update_libs.sh

  # Build and install
  - cd TRAVIS_BUILD_DIR
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=RELEASE ..

script: make

