language: cpp

# This method for installing apt-based dependencies works in
# container-based build (sudoless). Should use it if possible.
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8 # Get -std=c++11 support
    - g++-4.8

before_install:
  - sudo add-apt-repository ppa:apokluda/boost1.53 --yes
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -y g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install:
  - sudo apt-get install -y 
  - sudo apt-get install -y libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - sudo apt-get install -y doxygen
  - sudo apt-get install -y libboost1.53-all-dev

before_script:
  # Install OpenCV 3.0
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local ..
  - make -j1
  - sudo make -j1 install

  # Build and install
  - cd $TRAVIS_BUILD_DIR
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=DEBUG ..

script: make && make test
