install:
  - wget http://sourceforge.net/projects/boost/files/latest/download?source=files
  - tar -xf download
  - cd boost*
  - ./bootstrap.sh
  - cd ..
  - sudo cp -r boost* /opt
  - cd opt/boost*/
  - sudo ./b2 --with-program_options --with_system --with_thread
  - sudo apt-get update
  - sudo apt-get install libopencv-dev
  - cd src/backsubtractor
  - g++ BackgroundSubtractor.cpp main.cpp `pkg-config opencv --cflags --libs` -o test
