language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get install libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - sudo apt-get install libboost-all-dev
  - cd ~
  - ls

install:
  
  # Install OpenCV 3.0
  - cd ~
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local ..
  - make
  - sudo make install

  # RapidJSON and cpptoml
  - cd ~
  - cd jonnew/Oat/lib
  - sudo ./update_libs.sh

  # Build and install
  - cd ~
  - cd jonnew/Oat
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=RELEASE
  - make
  - make install

