language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - sudo apt-get install -y doxygen
  - sudo apt-get install -y libboost-all-dev

before_script:
  # Install OpenCV 3.0
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local ..
  - make -j1
  - sudo make -j1 install

  # RapidJSON and cpptoml
  - cd $TRAVIS_BUILD_DIR
  - cd lib
  - sudo ./update_libs.sh

  # Build and install
  - cd $TRAVIS_BUILD_DIR
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=RELEASE ..

script: make

