before_script:
  - wget http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz/download
  - tar -xf download
  - cd boost_1_58_0
  - ./bootstrap.sh
  - sudo ./b2 install

install:
  - echo $OKTEST
