# Example configuration file for the framefilt component
# Configuration options for each component TYPE are shown
# To use them:
#
# ``` bash
# ./framefilt TYPE SOURCE SINK -c config.toml -k TYPE
# ```

[bsub]
background = "background.png"       # Path to static background image

[mask]
mask = "mask.png"                   # Path to mask image

[mog]
learning_coeff = 0.0                # Learning coefficient to update model of image background
                                    # 0.0 - No update after initial model formation
                                    # 1.0 - Replace model on each new frame
