# Example configuration file for the framefilt component
# Configuration options for each component TYPE are shown
# To use them:
#
# ``` bash
# ./framefilt TYPE SOURCE SINK -c config.toml -k TYPE
# ```

[bsub]
background = "background.png"

[mask]
mask = "mask.png"
