# Example camera configuration file
# - Every viable option is listed with a reasonable value
# - Some options are mutualy exclusive (e.g. Camera exposure, shutter, and gain),
# and therefore will be overriden if more than one is specified.
# - Commented options revert to their default state, ususuall "off"
# - Invalid parameters are ignored (TODO: with a warning)

# Camera (gige) -------------------------

[maze_cam]
index = 0 							# Index of camera on the bus
exposure = -2.0							# EV
shutter = 3 							# ms (ignored if exposure on)
gain = 0 							# dB (ignored if exposure on)
#white_bal = {red = 500, blue = 800}                            # If not supplied, defaults to "off"
#roi = {x_offset = 0, y_offset = 0, width = 728, height = 728}   # Region of interest, pixels
trigger_on = false						# If false, free run
trigger_polarity = 1                                            # Rising edge active
trigger_mode = 14						# 14 = Overlapped Exposure/Readout Mode (see Camera manual)
                                                                # 7  = Software trigger
trigger_source = 0						# GPIO pin that trigger will be sent to
calibration_file = "calibration.yml"
