# Example configuration file for the frameserve component
# Configuration options for each component TYPE are shown
# To use them:
#
# ``` bash
# ./frameserve TYPE SINK -c config.toml -k TYPE
# ```

[gige]
roi_mask = "mask.png"
index = 0 								# Index of camera on the bus
exposure = 0.0							# EV
shutter = 3 							# ms (ignored if exposure on)
gain = 0 								# dB (ignored if exposure on)
#white_bal = {red = 500, blue = 800}	# Defaults to "off"
roi = {x_offset = 300, y_offset = 0, width = 728, height = 728} # Region of interest, pixels
trigger_on = false						# If false, free run
trigger_polarity = 1					# Rising edge active
trigger_mode = 14						# 14 = Overlapped Exposure/Readout Mode (see Camera manual)
										# 7  = Software trigger
trigger_source = 0						# GPIO pin that trigger will be sent to
calibration_file = "calibration.yml" 	# Camera matrix, distorition coefficients for lens correction

[file]
frame_rate = 50.0                       # Hz 
#roi = {x_offset = 125, y_offset = 30, width = 490, height = 420} # Region of interest, pixels

[wcam]

