# Example configuration file for the positest component
# Configuration options for each component TYPE are shown
# To use them:
#
# ``` bash
# oat posigen TYPE SINK -c config.toml TYPE
# ```

[rand2D]
rate-hz = 0.25                      # Test position sample period in seconds
num-samples = 100                   # Number of position samples to produce.
                                    # Defaults to infinity.
room = [0.0, 0.0, 1000.0, 1000.0]   # The 'room' in which generated positions reside
                                    # specified as [x origin, y origin, width, height]
                                    # If generated positions extend beyond the
                                    # room boundaries they will re-enter on the
                                    # other side.
