# Example tracker configuration file
# - Every viable option is listed with a reasonable value
# - Some options are mutualy exclusive (e.g. Camera exposure, shutter, and gain),
# and therefore will be overriden if more than one is specified.
# - Commented options revert to their default state, ususuall "off"
# - Invalid parameters are ignored (TODO: with a warning)

# Camera (file) -------------------------

[file_cam]
frame_rate = 300.0 						# Hz

# Detector (hsv, blue) ----------------

[hsv]
erode = 0 								# Pixels
dilate = 15								# Pixels
tune = true                 			# Provide sliders for tuning hsv thresholds
h_thresholds = {min = 000, max = 256}	# Hue pass band
s_thresholds = {min = 215, max = 256}	# Saturation pass band
v_thresholds = {min = 000, max = 256}	# Value pass band

# Posifilt (kalman) ------------------

[kalman]
dt = 0.01 								# Sample period
not_found_timeout = 10.0				# Seconds
tune = true                 			# Provide sliders for tuning hsv thresholds
sig_accel = 10							# std of random accelerations (px/s^2)
sig_noise = 10							# std of measurement noise (px/s^2)
s_thresholds = {min = 215, max = 256}	# Saturation pass band
v_thresholds = {min = 000, max = 256}	# Value pass band
