# -- Recording --
[gige]
index = 0                               # Index of camera on the bus
exposure = 0.0                          # EV
shutter = 3                             # ms (ignored if exposure on)
gain = 0                                # dB (ignored if exposure on)
# Region of interest, pixels
roi = {x_offset = 300, y_offset = 0, width = 728, height = 728}
trigger_on = false                      # If false, free run
trigger_polarity = 1                    # Rising edge active
trigger_mode = 14                       # 14 = Overlapped Exposure/Readout Mode (see Camera manual)
                                        # 7  = Software trigger
trigger_source = 0                      # GPIO pin that trigger will be sent to

# -- Post record processing --
[video]
frame_rate = 10.0                      # Hz

[mask]
mask = "./mask_loose.png"

[hsv_orange]
erode = 1                               # Pixels
dilate = 8                              # Pixels
tune = false                            # Provide sliders for tuning hsv thresholds
min_area = 20                           #
max_area = 1000
h_thresholds = {min = 000, max = 060}   # Hue pass band
s_thresholds = {min = 000, max = 256}   # Saturation pass band
v_thresholds = {min = 226, max = 256}   # Value pass band

[hsv_blue]
erode = 1                               # Pixels
dilate = 8                              # Pixels
tune = false                            # Provide sliders for tuning hsv thresholds
min_area = 20                           #
max_area = 1000
h_thresholds = {min = 060, max = 100}   # Hue pass band
s_thresholds = {min = 000, max = 256}   # Saturation pass band
v_thresholds = {min = 087, max = 256}   # Value pass band

[mean]
heading_anchor = 0                      # Position to use as heading anchor

[kalman]
dt = 0.03333333                         # Real-world sample period, seconds
                                        # In this case, this is from frame rate of VT1 video
                                        # which is 30 FPS
timeout = 10.0                          # Seconds
sigma_accel = 1000.0                    # Pixels/sec^2
sigma_noise = 7.0                       # Noise measurement (pixels)
tune = true                             # Use the GUI to tweak parameters

[region]
CN = [[336.00, 272.50],
      [290.00, 310.00],
      [289.00, 369.50],
      [332.67, 417.33],
      [389.33, 413.33],
      [430.00, 375.33],
      [433.33, 319.33],
      [395.00, 272.00]]

R0 = [[644.00, 380.00],
      [717.33, 386.67],
      [714.00, 316.67],
      [645.33, 320.33]]

R1 = [[544.00, 590.00],
      [597.33, 647.33],
      [641.33, 601.33],
      [590.00, 545.33]]

R2 = [[321.33, 644.67],
      [318.00, 715.33],
      [388.00, 715.33],
      [388.00, 646.67]]

R3 = [[133.33, 517.33],
      [64.00,  578.67],
      [106.67, 622.00],
      [169.33, 570.00]]

R4 = [[90.00,  303.00],
      [21.33, 301.33],
      [15.33, 360.67],
      [87.00,  360.00]]

R5 = [[204.00, 134.00],
      [162.67, 84.00 ],
      [113.33, 124.67],
      [158.67, 171.33]]

R6 = [[402.67, 83.33],
      [404.67, 29.33],
      [341.33, 26.00],
      [338.00, 85.33]]

R7 = [[576.67, 190.67],
      [625.33, 142.67],
      [588.00, 108.00],
      [537.33, 147.33]]

A0 = [[433.33, 319.33],
      [645.33, 320.33],
      [644.00, 380.00],
      [430.00, 375.33]]

A1 = [[430.00, 375.33],
      [590.00, 545.33],
      [544.00, 590.00],
      [389.33, 413.33]]

A2 = [[389.33, 413.33],
      [388.00, 646.67],
      [321.33, 644.67],
      [332.67, 417.33]]

A3 = [[332.67, 417.33],
      [169.33, 570.00],
      [133.33, 517.33],
      [289.00, 369.50]]

A4 = [[289.00, 369.50],
      [87.00,  360.00],
      [90.00,  303.00],
      [290.00, 310.00]]

A5 = [[290.00, 310.00],
      [158.67, 171.33],
      [204.00, 134.00],
      [336.00, 272.50]]

A6 = [[336.00, 272.50],
      [338.00, 85.33 ],
      [402.67, 83.33 ],
      [395.00, 272.00]]

A7 = [[395.00, 272.00],
      [537.33, 147.33],
      [576.67, 190.67],
      [433.33, 319.33]]

