# Example configuration file for the posidet component
# Configuration options for each component TYPE are shown
# To use them:
#
# ``` bash
# oat posidet TYPE SOURCE SINK -c config.toml -k TYPE
# ```

[hsv]
tune = true                             # Provide sliders for tuning hsv parameters
erode = 1                               # Pixels, candidate object erosion kernel size                        
dilate = 7                              # Pixels, candiate object dilation kernal size
min_area = 4                            # Pixels^2, minimum object area 
max_area = 1000                         # Pixels^2, maximum object area
h_thresholds = {min = 030, max = 080}   # Hue pass band
s_thresholds = {min = 140, max = 250}   # Saturation pass band 
v_thresholds = {min = 000, max = 070}   # Value pass band

[diff]
tune = true                             # Provide sliders for tuning diff parameters
blur = 10 								# Pixels, blurring kernel size (normalized box filter)
diff_threshold = 20 					# Intensity difference threshold

