# Example GigE camera configuration file.

[camera]  		# Camera configuration
#name = "maze_cam" 	# (TODO: remove)Server name
index = 0 		# Index of camera on the bus
exposure = 0.0          # EV, if specified, shutter and gain are ignored
shutter = 3 		# ms
gain = 0 		# dB
white_bal = {red = 500, blue = 800} 	
roi = {x_offset = 0, y_offset = 0, width = 728, height = 728} # Pixels

# Trigger
[camera.trigger]
on = true               # If trigger is not specified, or this is false, free run the camera
polarity = true         # Rising edge active
mode = 14               # Overlapped Exposure/Readout Mode (see Camera manual)
source = 0              # GPIO pin that trigger will be sent to
