# Example GigE camera configuration file.

[maze_cam]  		# Camera configuration
index = 0 		# Index of camera on the bus
exposure = -2.5          # EV, if specified, shutter and gain are ignored
shutter = 3 		# ms
gain = 0 		# dB
#white_bal = {red = 500, blue = 800} 	
roi = {x_offset = 0, y_offset = 0, width = 728, height = 728} # Pixels

# Trigger
[maze_cam.trigger]
on = true               # If trigger is not specified, or this is false, free run the camera
polarity = true         # Rising edge active
mode = 14               # Overlapped Exposure/Readout Mode (see Camera manual)
source = 0              # GPIO pin that trigger will be sent to

## Blue HSV detector
[blue_hsv]
position = "posterior"
erode = 2 			# pixels
dilate = 20 			# pixels
hsv_tune = true                 # provide sliders for tuning hsv thresholds
h_thresholds = {min = 106, max = 126}
s_thresholds = {min = 69, max = 256}
v_thresholds = {min = 180, max = 256}
decorate = true 	# decorate the output image with position info:

## Blue HSV detector
[orange_hsv]
position = "posterior"
erode = 2 			# pixels
dilate = 20 			# pixels
hsv_tune = true                 # provide sliders for tuning hsv thresholds
h_thresholds = {min = 75, max = 171}
s_thresholds = {min = 87, max = 204}
v_thresholds = {min = 180, max = 256}
decorate = true 	# decorate the output image with position info:
