# Example configuration file for the positest component
# Configuration options for each component TYPE are shown
# To use them:
#
# ``` bash
# ./frameserve TYPE SINK -c config.toml -k TYPE
# ```

[rand2D]
dt = 0.25 						# Test position sample period in seconds
