# Example tracker configuration file
# - Every viable option is listed with a reasonable value
# - Some options are mutualy exclusive (e.g. Camera exposure, shutter, and gain),
# and therefore will be overriden if more than one is specified.
# - Commented options revert to their default state, ususuall "off"
# - Invalid parameters are ignored (TODO: with a warning)

# Camera --------------------------------

[maze_cam]
index = 0 								# Index of camera on the bus
exposure = -2.0							# EV
shutter = 3 							# ms (ignored if exposure on)
gain = 0 								# dB (ignored if exposure on)
#white_bal = {red = 500, blue = 800}	# Defaults to "off"
roi = {x_offset = 0,					# Regio of interest, pixels
	   y_offset = 0,
	   width = 728,
	   height = 728}

[maze_cam.trigger]						# If trigger not specified, free run
on = true								# If false, free run
polarity = true							# Rising edge active
mode = 14								# Overlapped Exposure/Readout Mode (see Camera manual)
source = 0								# GPIO pin that trigger will be sent to

# Blue HSV detector ---------------------

[blue_hsv]
erode = 0 								# Pixels
dilate = 10								# Pixels
tune = true                 			# Provide sliders for tuning hsv thresholds
h_thresholds = {min = 106, max = 126}	# Hue pass band
s_thresholds = {min = 237, max = 256}	# Saturation pass band
v_thresholds = {min = 150, max = 256}	# Value pass band

# Orange HSV detector--------------------

[orange_hsv]
erode = 2 								# Pixels
dilate = 10 							# Pixels
tune = true								# Provide sliders for tuning hsv thresholds
h_thresholds = {min = 0, max = 32}		# Hue pass band band
s_thresholds = {min = 230, max = 256}	# Saturation pass band
v_thresholds = {min = 180, max = 256}	# Value pass band
