# Example tracker configuration file
# - Every viable option is listed with a reasonable value
# - Some options are mutualy exclusive (e.g. Camera exposure, shutter, and gain),
# and therefore will be overriden if more than one is specified.
# - Commented options revert to their default state, ususuall "off"
# - Invalid parameters are ignored (TODO: with a warning)

# Camera (file) -------------------------

[file_cam]
frame_rate = 50.0 						# Hz
roi = {x_offset = 125, y_offset = 30, width = 490, height = 420} # Region of interest, pixels

# Detector (hsv, blue) ----------------

[hsv]
erode = 0 								# Pixels
dilate = 15								# Pixel
tune = true                 			# Provide sliders for tuning hsv thresholds
h_thresholds = {min = 000, max = 256}	# Hue pass band
s_thresholds = {min = 215, max = 256}	# Saturation pass band
v_thresholds = {min = 000, max = 256}	# Value pass band

# Posifilt (kalman) ------------------

[kalman]
dt = 0.02								# Sample period, seconds (Should be automatically provided)
not_found_timeout = 10.0				# Seconds
sigma_accel = 30.0 						# Meters/sec^2
sigma_noise = 0.5						# Noise measurement (meters)
tune = false                             # Use the GUI to tweak parameters
