# Example tracker configuration file.

###
[io] 			# File saving/streaming
[io.save]
auto_name = true 	# Automatically name files using timestamp
subject = "3(3)"
experiment = "test"
data_format = "combined"

[io.stream]
client_ip = "100.100.100.100"
format = "json"

###
[camera]  		# Camera configuration
index = 0
exposure = 0.0          # EV, if specified, shutter and gain are ignored
shutter = 3 		# ms
gain = 0 		# dB
white_bal = {red = 500, blue = 800} 	
roi = {x_offset = 0, y_offset = 0, width = 728, height = 728} # Pixels

# Trigger
[camera.trigger]
on = true               # If trigger is not specified, or this is false, free run the camera
polarity = true         # Rising edge active
mode = 14               # Overlapped Exposure/Readout Mode (see Camera manual)
source = 0              # GPIO pin that trigger will be sent to

###
[tracker] 			# Tracker configuration

# Image registration sequence for transforming
# pixels to mm
[tracker.registration]  
on = false
method = "linear-interp"

# Background subtraction
[tracker.background_subtract]
show = false

# Color detection. The number of detection tables
# specified in this array dictate the number of tracked
# objects available to the combiner
[[tracker.detector]]
name = "blue"
show = true
position = "anterior"
erode = 2 			# pixels
dilate = 8 			# pixels
hsv_tune = true                 # provide sliders for tuning hsv thresholds
h_thresholds = {min = 106, max = 126}
s_thresholds = {min = 69, max = 256}
v_thresholds = {min = 180, max = 256}

 
[[tracker.detector]]
name = "orange"
show = true
position = "posterior"
erode = 2 			# pixels
dilate = 8 			# pixels
hsv_tune = true                 # provide sliders for tuning hsv thresholds
h_thresholds = {min = 0, max = 20}
s_thresholds = {min = 99, max = 210}
v_thresholds = {min = 49, max = 256}

# Combiner to combine the objects produced by the detectors
# into unified position and heading estimate. The selected
# method must be appropriate for the number of detectors 
# specified.
[tracker.combiner]
method = "2-point-interp"
target = "middle"
show = true


