# Example configuration file for the posicom component
# Configuration options for each component TYPE are shown
# To use them:
#
# ``` bash
# oat posicom TYPE SOURCES SINK -c config.toml -k TYPE
# ```

[mean]
generate-heading = true; 					# Should a heading be generated instead
											# of taking the mean of the sources?
heading-anchor = 0; 						# Position used has anchor when calculing
											# mean vector to other SOURCE positions
